COMMA = ","
COLON = ":"
LEFT_BRACKET = "["
RIGHT_BRACKET = "]"
LEFT_BRACE = "{"
RIGHT_BRACE = "}"
QUOTE = '"'
SYNTAX = [COMMA, COLON, LEFT_BRACKET, RIGHT_BRACKET, LEFT_BRACE, RIGHT_BRACE]

WHITESPACE = [" ", "\t", "\b", "\n", "\r"]
